# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  #config.vm.box = "fso/xenial64-desktop"
  config.vm.box = "bento/ubuntu-16.04"
  #config.disksize.size = "20GB"

  # VirtualBox specific configuration
  config.vm.provider "virtualbox" do |vb|
    vb.name = "P4-learning"
    vb.gui = true
    vb.memory = 4096
    vb.cpus = 3
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]

    vb.customize ["storageattach", :id,
                "--storagectl", "IDE Controller",
                "--port", "0", "--device", "0",
                "--type", "dvddrive",
                "--medium", "emptydrive"]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']

    #--stroagectl can be "IDE Controller" in other Operating Systems
  end
  
 config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true

 # for 'vagrant ssh'
 # config.ssh.port = 2223

 #config.vm.network :private_network, ip: "192.168.200.10"
 #config.vm.synced_folder '.', '/vagrant', disabled: true #disables sharing
 config.vm.hostname = "p4"

 #provisioning the VM


 #fixes the lock problem
 #config.vm.provision "fix-no-tty", type: "shell" do |s|
 #  s.privileged = true
 #  s.inline = "sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n \\|\\| true/' /root/.profile"
 #end

 #config.vm.provision "disable-apt-periodic-updates", type: "shell" do |s|
 #  s.privileged = true
 #  s.inline = "echo 'APT::Periodic::Enable \"0\";' > /etc/apt/apt.conf.d/02periodic"
 #end

 #config.vm.provision "file", source: "vm_files/p4_16-mode.el", destination: "/home/vagrant/p4_16-mode.el"
 #config.vm.provision "file", source: "vm_files/p4.vim",        destination: "/home/vagrant/p4.vim"
 #config.vm.provision "file", source: "vm_files/nsg-logo.png",        destination: "/home/vagrant/nsg-logo.png"
 #config.vm.provision "file", source: "vm_files/tmux.conf",        destination: "/home/vagrant/.tmux.conf"
 config.vm.provision "shell", path: "bin/dos2unix.sh"
 config.vm.provision "shell", path: "bin/root-bootstrap.sh"

end
